# Generated by Django 4.2.4 on 2023-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('age', models.IntegerField()),
                ('identity', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
